version: '3.9'

networks:
    ldap-demo-net:
        name: ldap-demo-net
        external: false
        driver: bridge
services:
    solace:
        image: solace/solace-pubsub-standard:latest
        container_name: solacebroker
        hostname: solacebroker
        networks:
            - ldap-demo-net
        shm_size: 1g
        ulimits:
            core: 1
            nofile:
                soft: 2448
                hard: 6592
        deploy:
            restart_policy:
                condition: on-failure
                max_attempts: 1
        ports:
      # Port Mappings:  With the exception of SMF, ports are mapped straight
      # through from host to container.  This may result in port collisions on
      # commonly used ports that will cause failure of the container to start.
            - 5672:5672  # AMQP Default VPN
            - 1883:1883  # MQTT Default VPN
            - 8000:8000  # MQTT Default VPN over WebSockets
            - 8080:8080  # SEMP / PubSub+ Manager
            - 9000:9000  # REST Default VPN
            - 55554:55555  # SMF
            - 55003:55003  # SMF Compressed
            - 2222:2222  # SSH connection to CLI
            - 8008:8008  # Web transport
        environment:
            - username_admin_globalaccesslevel=admin
            - username_admin_password=admin
            - system_scaling_maxconnectioncount=1000      
            - system_scaling_maxkafkabridgecount=10
            - system_scaling_maxkafkabrokerconnectioncount=300
    openldap:
        image: bitnami/openldap:latest
        container_name: openldap-demo
        ports:
            - '1389:1389'
            - '1636:1636'
        environment:
            - LDAP_ADMIN_USERNAME=admin
            - LDAP_ADMIN_PASSWORD=adminpassword
        networks:
            - ldap-demo-net
        volumes:
            - 'openldap_data:/bitnami/openldap'
            - './ldap/schemas/:/schemas'
            - './ldap/ldifs/:/ldifs'
volumes:
    openldap_data:
        driver: local
